"""
浅色主题定义
"""

from .tokens import ThemeTokens

# 浅色主题令牌
LIGHT: ThemeTokens = {
    "bg_main": "#f7f7f9",
    "bg_secondary": "#ffffff",
    "bg_tertiary": "#f0f1f3",
    "bg_panel": "#fbfbfd",
    "bg_hover": "#eef0f4",
    "bg_hover_strong": "#e6e8ee",
    "border": "#d0d7de",
    "border_light": "#e6e8ee",
    "text": "#1f2328",
    "text_muted": "#57606a",
    "text_dim": "#8c959f",
    "text_on_accent": "#ffffff",
    "icon": "#57606a",
    "accent": "#0969da",
    "accent_hover": "#0758b8",
    "accent_blue": "#0969da",
    "accent_link": "#0969da",
    "selection_bg": "#cfe8ff",
    "primary_green": "#2da44e",
    "primary_green_hover": "#2c974b",
    "primary_green_pressed": "#238636",
    "danger": "#cf222e",
    "danger_hover": "#a40e26",
    "danger_pressed": "#82071e",
    "danger_checked": "#cf222e",
    "neutral": "#6e7781",
    "neutral_hover": "#5b646e",
    "neutral_pressed": "#48515a",
    "success": "#2da44e",
    "warning": "#bf8700",
    # Tooltips: keep dark for readability
    "tooltip_bg": "#1f2328",
    "tooltip_border": "#3d444d",
    "tooltip_text": "#f0f0f0",
    "radius": "4px",
    "radius_lg": "6px",
    "font_main": '"Segoe UI", "Microsoft YaHei", sans-serif',
    "font_mono": '"Consolas", "Courier New", monospace',
    "size_base": "10pt",
    "size_small": "9pt",
    "size_large": "11pt",
    "space_sm": "4px",
    "space_md": "8px",
    "space_lg": "12px",
    # Buttons (generic)
    "btn_bg": "#f6f8fa",
    "btn_bg_hover": "#eef2f6",
    "btn_bg_pressed": "#e7ebef",
    "btn_border": "#d0d7de",
    "btn_border_hover": "#b6bec8",
    "btn_text": "#1f2328",
    "btn_disabled_bg": "#f6f8fa",
    "btn_disabled_border": "#e6e8ee",
    "btn_disabled_text": "#8c959f",
    # Scrollbar handles
    "scroll_handle": "rgba(0, 0, 0, 0.18)",
    "scroll_handle_hover": "rgba(0, 0, 0, 0.28)",
    "scroll_handle_pressed": "rgba(0, 0, 0, 0.38)",
    # Tree branch icons (QSS cannot tint; pick per-theme assets)
    "tree_branch_closed_icon": "ur_print_fdm/ui/resources/icons/collapse_light.svg",
    "tree_branch_open_icon": "ur_print_fdm/ui/resources/icons/expand_light.svg",
    # Code editor syntax highlighting
    "syntax_operator": "#57606a",
    "syntax_comment": "#6a737d",
    "syntax_keyword": "#0550ae",
    "syntax_number": "#953800",
    "syntax_string": "#0a3069",
    "syntax_function": "#8250df",
}
